name: helpinghand
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^3.3.3
  jwt_decoder: ^1.0.3
  flutter_screenutil: ^4.0.2
  flutter_svg: ^0.19.1
  line_awesome_flutter: ^1.0.1
  contact_picker: ^0.0.2
  font_awesome_flutter: ^8.11.0
  hexcolor: ^2.0.5
  pin_code_fields: ^6.1.0
  flare_flutter: ^2.0.6
  flutter_masked_text: ^0.8.0
  flutter_local_notifications: ^8.1.1+1
  toast: ^0.1.5
  flutter_spinkit: ^4.1.2
  skeleton_text: ^2.0.2
  animated_text_kit: ^3.1.0
  charts_flutter: ^0.10.0
  share: ^0.6.5+4
  fl_chart: ^0.12.3
  overlay_support: ^1.2.0
  firebase_database:
  splashscreen: 1.2.0
  flutter_signin_button:
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_storage: ^10.0.3
  google_sign_in: ^5.0.0
  firebase_analytics:
  sign_in_with_apple: ^2.5.2
  crypto: ^2.1.5
  flutter_facebook_auth: ^3.5.0
  flutter_zoom_drawer: ^1.0.5
  flutter_platform_widgets: ^1.9.5
  provider: ^5.0.0
  easy_localization:
  video_player: ^2.1.14
  image_picker: any
  image_picker_for_web: ^2.1.3
  camera: ^0.9.2+2
  connectivity: ^3.0.6
  path_provider: ^2.0.2
  path: ^1.8.0
  permission_handler: ^8.1.4+2
  chat_bubbles: ^1.1.0
  cloud_firestore: ^2.5.1
  data_connection_checker: ^0.3.4
  intl: ^0.17.0
  fluttertoast: ^8.0.8
  camerawesome: ^0.3.0+1
  firebase_messaging: ^10.0.0
  holding_gesture: ^1.1.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/helpinghand.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/flare/
    - assets/fonts/
    - assets/langs/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600