library screens;

import 'dart:io';
import 'dart:async';
import 'package:data_connection_checker/data_connection_checker.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:helpinghand/fireBaseUtils/fire_store.dart';
import 'package:helpinghand/widgets/profile_list_item.dart';
import 'package:intl/intl.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:hexcolor/hexcolor.dart';
import 'package:flutter/cupertino.dart';
import 'package:provider/provider.dart';
import '../widgets/dialogs/dialogs.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:helpinghand/utils/constant.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:holding_gesture/holding_gesture.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:chat_bubbles/date_chips/date_chip.dart';
import 'package:helpinghand/widgets/camera/camera.dart';
import 'package:helpinghand/widgets/dialogs/dialogs.dart';
import 'package:helpinghand/utils/globals.dart' as globals;
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_zoom_drawer/flutter_zoom_drawer.dart';
import 'package:chat_bubbles/bubbles/bubble_special_one.dart';
import 'package:line_awesome_flutter/line_awesome_flutter.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:helpinghand/fireBaseUtils/firebase_authentication.dart';
import 'package:helpinghand/widgets/video_player/video_player.dart';
import 'package:flutter_platform_widgets/flutter_platform_widgets.dart';
import 'package:helpinghand/widgets/video_player/video_player_dialog.dart';


part 'login/login_screen.dart';
part 'settings/settings_screen.dart';
part 'profile/profile_screen.dart';
part 'register/register_screen.dart';
part 'page_structure/page_structure.dart';
part 'menu/menu_screen.dart';
part 'help/get_help_screen.dart';
part 'help/translate_screen.dart';
part 'help/my_profile.dart';
part 'help/all_requests.dart';
part 'help/community.dart';
part 'help/existing_signs.dart';
part 'help/recent_activity.dart';
part 'support/support_screen.dart';
part 'support/account/account_support.dart';